### PR TITLE
Fixed uicatalogapp and nativegesture tests to pass. All tests not passing yet.

### PR DESCRIPTION
**Pull request by thanhcs**
There is a problem when two sessions running in sequence use the same simulator device. When the first session ends, it shuts down the simulator. However, the second session will not find the simulator which is shutting down. I add codes to wait for the simulator shuts down successfully. 

The tests are fixed for the new version of both apps. I will try to fix the other tests if these changes are valid.

### CODE REVIEW

**Comment by mach6** [comment]
@thanhcs It's generally considered a good practice to squash your commits before submitting a PR. Please do this. Also, please check the content of your PR for problematic content. For example, I see a bunch of files in your PR with this in the filename - `Thanh’s MacBook Pro's conflicted copy 2015-03-08)`

**Comment by thanhcs** [comment]
Sorry about that. First time. Guide me if you see something I should do. I will fix what you just said asap.

**Comment by thanhcs** [comment]
Should I reorganize my commits and make a new pull request or this should be fine to you?

**Comment by thanhcs** [comment]
I fixed it.

**Comment by thanhcs** [comment]
Absolutely right. I fixed it. The logging is turned off by default in SimulatorSetting class. I haven't figured out how to turn it on, but I think it's turned off intentionally.

**Comment by thanhcs** [comment]
To be clear what I did:
1. I update the new versions of UICatalog, PPNQASampleApp, InternationalMountain apps from sources:
   - UICatalog: https://developer.apple.com/library/ios/samplecode/UICatalog/Introduction/Intro.html (at the time I download it, its version is 11.3)
   - PPNQASampleApp : https://github.com/darraghgrace/ios-driver-sample-app
   - InternationalMountains: https://developer.apple.com/library/ios/samplecode/InternationalMountains/Introduction/Intro.html#//apple_ref/doc/uid/DTS40008756-Intro-DontLinkElementID_2
2. Update e2e.uicatalogapp and e2e.nativegesture test packages to be compatible with the newly updated apps (from step 1). All tests in these packages passed. The other tests do not pass, but will be fixed in another pull request.
3. Adding logging and exception handling when finding device UUID
   - In DeviceUUIDsMap.java: 
     - Fixed regex matching logic to match with another device status: "Shutting Down". Get status of all simulators and put it in a HashMap (simulatorState)
   - In SimulatorSettings.java:
     - Checking if there is an UUID for the requested device. If there isn't, throw NotFoundException. If there is, continue to check the state of that device.
     - If the status of that device is "Shutting Down", wait `SLEEP_TIME_BETWEEN_TRIES` and then re-check its status. The number of the trying loop will be controlled by `NUMBER_TRIES_GETTING_UUID` constant variable.
     - If after `NUMBER_TRIES_GETTING_UUID` retry times, the device is still in `"Shutting Down"` state, raise an `NotActiveException` with information about it.
     - if the device passes the `"Shutting Down"` state, simply return its UUID.

Thanks professor @mmccartney and Derek (@derekngo)

**Comment by thanhcs** [comment]
change regex in DeviceUUIDsMap to catch all simulator's states - recommended by professor @mmccartney

**Pull request closed without merging**
