### PR TITLE
Update to selenium 2.45.0 and latest libimobiledevice-wrapper commit

### PR DESCRIPTION
**Pull request by mach6**
@lukeis per our conversation.

### CODE REVIEW

**Comment by lukeis** [comment]
:+1:

**Comment by mach6** [comment]
@lukeis running some more tests and holding off on this .. will merge when I feel more comfortable.

**Comment by mach6** [comment]
Well, unfortunately, this change seems to cause even more safari crashes. Looks like the branch needs additional changes.

**Comment by mach6** [comment]
closing this PR as further changes are needed and to prevent merge until changes complete.

**Pull request closed without merging**
