### PR TITLE
Improved Concurrency and Stability

### PR DESCRIPTION
**Pull request by adataylor**
**Overview**
There are three main diffs here:
1) Using a more concise system of futures to await and find responses to commands, instead of the more complex system of finders [0b2fb437792b8376620ccde9218002d2ff9d6040]
2) Use a monitor system instead of WebSynchronizer, and strengthen its guarantees. [fac49627fcad51b5702c39db34effe920deb33d8]
3) Communicate directly with the chosen app by bundle id, and clarify the distinction between bundleId and applicationIdentifier. [9f5c7a59e3d21c5a65e19f8a686be2816b6f49d4]

Minor cleanup includes recognizing applicationUpdated messages [adad7b5269b2ba8d3edfa0cb7c02f964bd290802], and warnings when devices are removed due to errors. [8e7c5c2b39f5b81eb925335c134e1b38da0c09ae]

**1) Futures system [0b2fb437792b8376620ccde9218002d2ff9d6040]**
For each command, there is a corresponding future, and as soon as a matching response is processed, it is reported directly to its future, allowing all threads waiting on the value to proceed. For a developer, this makes individual command responses and timeouts easier to pinpoint, and is more readable. Also have noted slight performance uptick.

Previously, ios-driver used a more indirect system of cycling through finders in order to check if a response to a given command id has been received. This lead to several confusing layers of threads, and more difficult ramp up and debugging.

Note that the popups AlertDetector would have detected and thrown errors on are caught by timeouts, so this edge case can be consolidated.

**2) Use a monitor system for better concurrency guarantees**[fac49627fcad51b5702c39db34effe920deb33d8]
The original WebSynchronizer relies on locks only being signaled in cases where everything is going according to plan. However, there is no notification on timeouts, and the app often proceeds forward without the device correctly loaded, or the _desired_ app loaded. System of monitors makes guarantees explicit, and makes timeouts or individual failures to load components more obvious.

**3) Look for Bundle Id directly [9f5c7a59e3d21c5a65e19f8a686be2816b6f49d4]**
When launching, communicating with the application initially, or filtering messages, the application is never directly verified. When multiple "connectable" apps are found, it will often connect to the first one seen, which leads to both incorrect and inconsistent behavior.

Also note, in iOS8 the applicationIdentifier has a PID, the bundleId has the familiar com.apple.mobilesafari format. In iOS7, the applicationId is of the com.apple.mobilesafari format. Separated the cases when an individual instance is desired (applicationIdentifier) vs any instance of an application (bundleId).

Note that in iOS8, the application identifier which needs to be communicated with after safari launch is actually WebContent, not Safari directly. However, in iOS7, Safari remains the correct choice. External user behavior remains the same, however- just launch "Safari" as usual.

### CODE REVIEW

**Comment by adataylor** [comment]
@mmmulani what is the best idea for finding someone to approve?

**Comment by mmmulani** [comment]
ping @freynaud I don't really have time to review, sorry

**Comment by adataylor** [comment]
@lukeis any chance you could approve?

**Comment by lukeis** [comment]
@adataylor i haven't been very involved in this project for quite a while and this change is too big for me to easily understand its implications.

This project is in need of more people to take ownership of if it's going to continue... I don't use it anymore and since François left ebay, i'm not sure he does either.

@mmmulani do you think @adataylor should be made a Collaborator on this project?

**Comment by mmmulani** [comment]
yeah, that sounds good to me.

**Comment by lukeis** [comment]
@adataylor you have the access ;)  feel free to push changes that you feel confident in (having tests is a good thing as always!)

**Pull request merged**
