### PR TITLE
SendKeys() does not only send keys but also click 'Done' #251

### PR DESCRIPTION
**Pull request by azaytsev**
Adding a capability to allow the user to keep the keyboard on screen after sendkeys() command is issued. By default the 'Done' button will be clicked and the keyboard will be hidden

### CODE REVIEW

**Comment by mach6** [comment]
please be consistent w.r.t whitespace in this project. no tabs, 2 spaces per tab, 100 characters (max) per line

**Comment by azaytsev** [comment]
Fixed spacing. Added a license notice to a new test file

**Comment by mach6** [comment]
:+1: @freynaud @lukeis objections?

**Comment by azaytsev** [comment]
Messed up a merge while rebasing. Closing this pull request and re-opening a new one

**Pull request closed without merging**
