### PR TITLE
simulator have higher application size for mobile safari, need to find safari to trigger it

### PR DESCRIPTION
**Pull request by bijoyv**
seems like ios 8 simulators are giving varying application size, need to find safari to add a little more reliability

### CODE REVIEW

**Comment by mach6** [comment]
@bijoyv There is still tab characters in this change set. 

Also, What ios-driver issue is this commit aimed at addressing? Based on the change, I don't follow how you will more reliably connect to Safari when SDK >= 8.0. Especially, since you are ignoring the index where application name equalsIgnoreCase "Safari"

**Comment by bijoyv** [comment]
@mach6, I manually changed tabs to two spaces, but remote it seems like tabs are happening (have spaces in my local set and all is uptodate), shall check and correct it all subsequent PRs

This is to address the problems reported like 'WARNING NewSessionNHandler.safeStart Error starting the session.session created but application size=3.It should be 1. Do you have multiple tabs opened ?', basically in ios 8, it gives more application number when invoking mobile safari, and only one among them is actually the application instance we should talk (with application name Safari), still it fails at times but this should stop failure due to number of applications problem (https://github.com/ios-driver/ios-driver/issues/286)

**Comment by mach6** [comment]
@bijoyv I amended your commit to fix the whitespace and merged this to the `dev` branch

**Comment by phoebusliang** [comment]
Hi Dude, does this problem fix now in 0.6 snapshot?

**Pull request closed without merging**
