### PR TITLE
Revert "Merge pull request #11 from LegNeato/master"

### PR DESCRIPTION
**Pull request by nicegraham**
This reverts commit 0cffe8d84ff08c0e92e42d0deb52555f5189d342, reversing
changes made to 1d6d2860f7dbff37f859a976886e9425a48bfcf8.

### CODE REVIEW

**Comment by LegNeato** [comment]
Curious why you needed to do this? I can fix it, but can't find info why it was reverted.

**Comment by nicegraham** [comment]
it was in the wrong branch :) I merged it into Dev where all work is being
done.

**Comment by LegNeato** [comment]
Ah, thanks!

**Comment by nicegraham** [comment]
it'll be pushed to master as part of 0.7.0

**Pull request merged**
